name: Build Android

on:
  push:
    branches:
      - 'dreadmoor-init-17025123926669017520'
  pull_request:
    branches:
      - 'dreadmoor-init-17025123926669017520'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Fix iOS Path Error
        # This creates the dummy directory to prevent the OS Error: No such file or directory
        run: mkdir -p ios/Runner/Assets.xcassets/AppIcon.appiconset

      - name: Generate Launcher Icons
        # We target only android to be safe
        run: dart run flutter_launcher_icons:main --android
        continue-on-error: true 

      - name: Generate Drift Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Dreadmoor-Game-Build
          path: build/app/outputs/flutter-apk/app-release.apk
